language: python

before_install:
- bash ./corpus-client/scripts/install.sh

script:
- bash ./corpus-client/scripts/test.sh
- python -m unittest
- env CI=travis mamba

notifications:
  email: false
